### ISSUE TITLE
catkin_make failed

### ISSUE THREAD

**Issue by Shelfcol** [coincar-sim/lanelet2_interface_ros#1]
Sorry to bother you.I put lanelet2 and  mrt_cmake_modules  packages under catkin_ws/src, and lanelet2 catkin_make succeed.But when I put lanelet2_interface_ros  package under catkin_ws/src and catkin_make, it will display this error:

CMake Error at mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:80 (message):
  Package util_rviz is specified for autodepend but cmake variables are not
  defined.  Did you resolve dependencies?
Call Stack (most recent call first):
  lanelet_rviz_plugin_ros-release/CMakeLists.txt:16 (find_package)

Can you help me ?Looking forward to your reply.

**Comment by m-naumann** [comment]
Hi, I guess you also have the lanelet_rviz_plugin_ros in your workspace? In that case you must also add [util_rviz](https://github.com/coincar-sim/util_rviz) to your workspace, as it is a dependency of  lanelet_rviz_plugin_ros.

**Comment by Shelfcol** [comment]
Thank you for your reply. I just added util_rviz to my workspace,and catkin_make succeed without having lanelet_rviz_plugin_ros and lanelet2_interface_ros in my workspace.Then I put lanelet_rviz_plugin_ros in my workspace And it  have error like above.When I put lanelet2_interface_ros in my workspace alone,it also have same error.So I open mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake,and delete the message at 80: 
 message(FATAL_ERROR "Package ${other_package} is specified for autodepend but cmake variables are not defined. Did you resolve dependencies?"). And it succeeded.No error.I don't know if this method has hidden trouble?Looking forward to your reply,thank you.

**Comment by m-naumann** [comment]
That's probably due to a wrong build order. We recommend to use `catkin build` instead of `catkin_make`, as explained for example [here](https://github.com/coincar-sim/coincarsim_getting_started#3a-set-up-and-build-the-workspace-yourself) or [here](https://github.com/coincar-sim/coincarsim_getting_started/issues/1). I guess this solves your problem without just deleting the error messages ;)

**Comment by Shelfcol** [comment]
I am very interested the car simulation of your given link with lanelet, I will study it carefully. Thank you.
