### ISSUE TITLE
map_frame_to_utm_tf_publisher doesnt wait for parameters

### ISSUE THREAD

**Issue by PPeltzer** [coincar-sim/lanelet2_interface_ros#4]
In [map_frame_to_utm_tf_publisher.py](https://github.com/coincar-sim/lanelet2_interface_ros/blob/3f813442abcd792744ea40bf9dee2cdac87d68f7/scripts/map_frame_to_utm_tf_publisher.py#L60), the following loop is supposed to stall the node until all `/lanelet2_interface_ros/` rosparams are available:

```
    for i in range(3000):
        lat_origin = float(rospy.get_param("/lanelet2_interface_ros/lat_origin"))
        lon_origin = float(rospy.get_param("/lanelet2_interface_ros/lon_origin"))

        map_frame_id = rospy.get_param("/lanelet2_interface_ros/map_frame_id")
        actual_utm_with_no_offset_frame_id = rospy.get_param(
            "/lanelet2_interface_ros/actual_utm_with_no_offset_frame_id")
        if lat_origin is not None and lon_origin is not None \
                and map_frame_id is not None and actual_utm_with_no_offset_frame_id is not None:
            init = True
            break

        rospy.sleep(0.01)

    if not init:
        rospy.logerr("map_frame_to_utm_tf_publisher: Could not initialize")
        exit()
```

However, [get_param](http://wiki.ros.org/rospy/Overview/Parameter%20Server) actually raises a `KeyError` if the parameter is not present on the parameter server. Therefore, the whole loop is kinda meaningless, because if the parameters are present, the `is not None` checks will never fail and if they are not present, the script will exit due to the exception. By handling the exception e.g. in the following way
```
        try:
            map_frame_id = rospy.get_param("/lanelet2_interface_ros/map_frame_id")
        except Exception:
            pass
```
the checks will be useful again. However, you might need some special handling for the `float` casts there.

**Comment by PPeltzer** [comment]
@m-naumann any comment on that? My framework requires the `/lanelet2_interface_ros/` parameters to be set after the launch and therefore I would like to utilize the loop above to stall the module (I've addressed that locally but it would be nice to see this upstream - I can open a MR if that helps).

**Comment by m-naumann** [comment]
Valid point. Thanks for bringing that up. 

I think a good solution would be to only check whether the params are set in the loop (in a function), and then react accordingly. Like

```python
def wait_for_params_successful:
    # loop: if params are there return True
    # return False

...

    if not wait_for_params_successful():
        rospy.logerr("map_frame_to_utm_tf_publisher: Could not initialize")
        exit()

    # set params
```

What do you think?

Looking forward to your PR
